title = "Hamdi Kerem Kucukengin"
baseURL = "https://hamdikucukengin.com/"
languageCode = "en-us"
theme = "ananke"
resourceDir = "../resources"

DefaultContentLanguage = "en"
SectionPagesMenu = "main"
enableRobotsTXT = true

[pagination]
pagerSize = 3

[languages]
[languages.en]
title = "Ananke"
weight = 1
contentDir = "content/en"
[languages.fr]
title = "Ananke Fr"
weight = 2
contentDir = "content/fr"

[sitemap]
changefreq = "monthly"
priority = 0.5
filename = "sitemap.xml"

[params]
description = "The last theme you ever need. Maybe."
background_color_class = "bg-black"
recent_posts_number = 3